### ISSUE TITLE
[BUG] Could not load dynamic library 'libcuda.so.1'

### ISSUE THREAD

**Issue by SebastianGergen** [dessa-oss/atlas#117]
**Platform & setup**
I am running Ubuntu server 18.04, I have a Geforce 1080, Driver Version: 440.64.00, and CUDA Version: 10.2 installed (output of nvidia-smi).
I installed Atlas on the server based on a python environment with python 3.6.x. 
I stated the atlas server with the "-g" flag (while starting the server it says that Atlas is using GPU with ID [0]) and I ran the submit command with the "--num-gpus 1" flag.

**Describe the bug**
When running a code using tensorflow gpu version I get to following error and execution is moved to CPU:

`2020-03-31 12:19:34.418493: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory

2020-03-31 12:19:34.418513: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)

2020-03-31 12:19:34.418534: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist`

However when I run code locally using the same tf version everything is fine, and running nvidia docker container works as well.

**To Reproduce**

**Expected behavior**
Use GPU and CUDA in tensorflow computation.

**Comment by mohammedri** [comment]
@SebastianGergen few questions:

1. Do you have https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)  installed?
2. Are you using a custom worker image?

**Comment by SebastianGergen** [comment]
1. Yes I did it according to the installation guide, plese find the result of 
`docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`
in the screenshot:

![nvidiasmi_redqueen](https://user-images.githubusercontent.com/46710310/78116868-33be7600-7405-11ea-99c6-6d6829788a46.png)

2. Not sure what exactly you mean. What custom worker image? I followed the installatin guide on https://docs.atlas.dessa.com/en/latest/team/on-prem-installation/ and use the master node as the worker itself, no extra worker nodes connected.

When I log in onto the server on which atlas-server is running, in a separate terminal I can successfully run and track scripts using tensorflow-gpu within a virtual env "locally" (similar to the hello world in https://docs.atlas.dessa.com/en/latest/linux-mac-installation/) and from my remote machine I can submit jobs to the atlas server successfully, but only as described only CPU execution of tensorflow works, not GPU.

**Comment by mohammedri** [comment]
Hey @SebastianGergen, seems like few others have faced that same error as yourself - seems like a CUDA linking issue. 

Could you try the steps here?
https://github.com/tensorflow/tensorflow/issues/4078#issuecomment-255129832

**Comment by SebastianGergen** [comment]
Hey @mohammedri can you tell me what the base image is, on which the job images are build when a job is submitted from my remote machine to the atlas system? Or where I can find the job creation/image creation part in the code? Maybe I can work on the problem by trying to create such an image on my own, on the machine.

**Comment by mohammedri** [comment]
Hey @SebastianGergen thanks for looking into this. 

The base image that is used to run GPU jobs `atlas-server start -g` is here: 
https://github.com/dessa-oss/atlas/blob/master/worker_images/tensorflow-gpu/Dockerfile

The base image that is used to run non-GPU jobs `atlas-server start` is this:
https://github.com/dessa-oss/atlas/blob/master/worker_images/tensorflow/Dockerfile

**Comment by SebastianGergen** [comment]
Thank @mohammedri I run into the same error when I start the image when i build it. However, when I exchange the image to tensorflow 
`FROM tensorflow/tensorflow:2.1.0-gpu-py3-jupyter` 
and start it with 
`docker run --runtime=nvidia -it test2`
i works:
`Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7551 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)`

Is it possible the modify the image template on my atlas installation and try that?

**Comment by mohammedri** [comment]
Hey @SebastianGergen , yes you can 
In fact you can use a fully custom docker image - here are the instructions for that: 
https://docs.atlas.dessa.com/en/latest/atlas-modes/scheduling/#custom-workers

**Comment by SebastianGergen** [comment]
By creating a custom tf2.1.0 worker image, I was able to run a job with my GPU. Thank you!

If you want to do the same here is my dockerfile:

'COPY ./requirements.txt /tmp/requirements.txt                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                       
RUN pip install --requirement /tmp/requirements.txt                                                                                                                                                                                                                            
RUN rm /tmp/requirements.txt                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                               
ENTRYPOINT ["python"] '

and the corresponding requirements.txt 

'requests
jsonschema==3.0.2
dill==0.2.8.2
google-api-python-client==1.7.3
google-auth-httplib2==0.0.3
google-cloud-storage==1.10.0
PyYAML==5.1.2
freezegun==0.3.12
flask-restful==0.3.7
Flask==1.1.1
Flask-Cors==3.0.8
pandas==0.23.3
promise==2.2.1
redis==3.3.11
slackclient==1.3.0
Werkzeug==0.16.0
boto3==1.9.86
boto==2.49.0
python-jose==3.0.1
python-keycloak==0.17.6
tabulate==0.8.3
docker==4.0.2
numpy
sklearn
pillow
wheel
requests'

So this does not seem to be a bug in atlas, but rather a problem with linked libraries to the tensorflow 1.13 docker image for me. I

**Comment by mohammedri** [comment]
Amazing, glad you were able to solve this @SebastianGergen and get started! Keep us in the loop of what you end up creating with Atlas! 

Cheers
